drop table T04_TRIP if exists;
drop table T03_PERMISSION if exists;
drop table T02_PERMISSION_TYPE if exists;
drop table T01_USER if exists;

CREATE TABLE "T01_USER"(
"C01_USER_ID" BIGINT auto_increment primary key,
"C01_USERNAME" VARCHAR NOT NULL,
"C01_PASSWORD" VARCHAR NOT NULL,
"C01_FIRSTNAME" VARCHAR NOT NULL,
"C01_LASTNAME" VARCHAR NOT NULL,
"C01_EMAIL" VARCHAR NOT NULL,
"C01_ENABLED" Boolean DEFAULT true NOT NULL
);

-------------------------------------------------------

CREATE TABLE "T02_PERMISSION_TYPE"(
"C02_PERMISSION_TYPE_ID" BIGINT NOT NULL primary key,
"C02_NAME" VARCHAR NOT NULL
);

--------------------------------------------------------

CREATE TABLE "T03_PERMISSION"(
"C03_USER_ID" BIGINT NOT NULL,
"C03_PERMISSION_TYPE_ID" BIGINT NOT NULL,
PRIMARY KEY (C03_USER_ID, C03_PERMISSION_TYPE_ID)
);

ALTER TABLE T03_PERMISSION ADD FOREIGN KEY (C03_PERMISSION_TYPE_ID) REFERENCES T02_PERMISSION_TYPE( C02_PERMISSION_TYPE_ID ) ;
ALTER TABLE T03_PERMISSION ADD FOREIGN KEY (C03_USER_ID)            REFERENCES T01_USER (C01_USER_ID);
--------------------------------------------------------

CREATE TABLE "T04_TRIP"(
"C04_TRIP_ID" BIGINT NOT NULL PRIMARY KEY,
"C04_USER_ID" BIGINT NOT NULL,
"C04_DESTINATION" VARCHAR NOT NULL,
"C04_START_DATE" DATE NOT NULL,
"C04_END_DATE" DATE NOT NULL,
"C04_COMMENT" VARCHAR NOT NULL
);

ALTER TABLE T04_TRIP ADD FOREIGN KEY (C04_USER_ID) REFERENCES T01_USER (C01_USER_ID);

