# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    time-zone: Europe/Prague
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
#    deserialization:
#      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

# dataSource
  datasource:
    url: jdbc:p6spy:h2:/opt/p/sandbox/2_core/data/h2.db;AUTO_SERVER=true
    username: TP
    password: TP
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth

#logging:
#  level:
#    org.springframework:
#      security: DEBUG